version: '3'
services:
  simulator:
    build: ./simulator
    ports:
      - "11111:11111"
    restart: on-failure:5
  trainsdb:
    build: ./db
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: trainleader
      MYSQL_USER: traincontroller
      MYSQL_PASSWORD: user_pwd
